version: 2
updates:
  # Enable updates for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "[dependabot][actions]"
    labels:
      - "dependencies"
      - "auto"
    reviewers:
      - "AuraFrameFxDev"

  # Enable updates for Gradle (Android/JVM)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "[dependabot][gradle]"
    labels:
      - "dependencies" 
      - "auto"
    reviewers:
      - "AuraFrameFxDev"
