[versions]
# ===== Project & Build Tools =====
agp = "9.0.0-alpha03"
kotlin = "2.2.20-RC"
ksp = "2.2.20-RC-2.0.2"
hilt = "2.57.1"
googleServices = "4.4.3"
openApiGenerator = "7.14.0"

# ===== Kotlin & Coroutines =====
kotlinReflect = "2.2.20-RC"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
coroutinesTest = "1.10.2"

# ===== AndroidX =====
activityCompose = "1.10.1"
animatedVectorDrawable = "1.2.0"
appcompat = "1.7.1"
archCoreTesting = "2.2.0"
composeBom = "2025.08.01"
coreKtx = "1.17.0"
espresso = "3.7.0"
extJunit = "1.3.0"
junitKtx = "1.3.0"
lifecycle = "2.9.3"
material = "1.12.0"
material3 = "1.3.2"
navigationCompose = "2.9.3"
roomVersion = "2.7.2"
androidxSecurity = "1.1.0"
workManager = "2.10.3"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTestRules = "1.7.0"

# ===== Google & Firebase =====
firebaseBom = "34.2.0"
firebaseCrashlytics = "3.0.6"
firebaseCrashlyticsKtx = "19.4.4"
firebasePerf = "2.0.1"
googleAuth = "21.4.0"
googleAuthApiPhone = "18.2.0"
googleIdentity = "18.1.0"

# ===== Networking =====
okhttp = "5.1.0"
retrofit = "3.0.0"

# ===== Hooking Frameworks =====
lsposed = "6.4"
yuki = "1.3.0"

# ===== Security & Utilities =====
bouncycastle = "1.81"
bcprovJdk18on = "1.81"
coilCompose = "2.7.0"
commonsCompress = "1.28.0"
gson = "2.13.1"
tink = "1.18.0"
xz = "1.10"
auraBackendApiGenerator = "1.0.0"

# ===== Code Quality, Docs & Debugging =====
detekt = "1.23.8"
dokka = "2.0.0"
kover = "0.9.1"
ktlint = "1.0.1"
leakcanary = "2.14"
spotless = "7.2.1"
symbolProcessingGradlePlugin = "2.2.10-2.0.2"

# ===== Testing =====
junit = "4.13.2"
junitJupiter = "5.13.4"
mockk = "1.14.5"
turbine = "1.2.1"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openApiGenerator" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# ===== Kotlin & Coroutines =====
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# ===== AndroidX - Core, Appcompat & Lifecycle =====
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-animated-vector-drawable = { group = "androidx.vectordrawable", name = "vectordrawable-animated", version.ref = "animatedVectorDrawable" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# ===== AndroidX - Compose =====
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# ===== Google - Hilt, Firebase, Play Services =====
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "22.5.0" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebaseCrashlyticsKtx" }
google-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "googleAuth" }
google-auth-api-phone = { group = "com.google.android.gms", name = "play-services-auth-api-phone", version.ref = "googleAuthApiPhone" }
google-identity = { group = "com.google.android.gms", name = "play-services-identity", version.ref = "googleIdentity" }

# ===== Database - Room =====
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }

# ===== Networking =====
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

# ===== Hooking Frameworks =====
lsposed = { module = "org.lsposed.lsplant:lsplant", version.ref = "lsposed" }
yuki = { module = "com.highcapable.yukihookapi:api", version.ref = "yuki" }
yuki-ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yuki" }

# ===== Security & Crypto =====
androidx-security = { group = "androidx.security", name = "security-crypto", version.ref = "androidxSecurity" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
conscrypt-android = { group = "org.conscrypt", name = "conscrypt-android", version = "2.5.3" }
tink = { group = "com.google.crypto.tink", name = "tink-android", version.ref = "tink" }

# ===== Code Quality, Debugging & Build Logic =====
aura-backend-api-generator = { module = "dev.aurakai.aura:aura-backend-api-generator", version.ref = "auraBackendApiGenerator" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
ktlint = { group = "com.pinterest", name = "ktlint", version.ref = "ktlint" }
leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
symbol-processing-gradle-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "symbolProcessingGradlePlugin" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }

# ===== Utilities =====
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commonsCompress" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.20.0" }
coreLibraryDesugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version = "2.1.5" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
xz = { group = "org.tukaani", name = "xz", version.ref = "xz" }

# ===== Testing =====
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
# --- Android Test ---
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.9.0" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "archCoreTesting" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
androidx-test-ext-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }


[bundles]
androidx-core = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "androidx-material"
]
compose-ui = [
    "androidx-activity-compose",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-navigation-compose"
]
coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-android"
]
firebase = [
    "firebase-analytics",
    "firebase-crashlytics"
]
network = [
    "retrofit",
    "retrofit-converter-kotlinx-serialization",
    "okhttp3-logging-interceptor",
    "kotlinx-serialization-json",
    "gson"
]
room = [
    "room-runtime",
    "room-ktx"
]
testing-unit = [
    "junit-jupiter",
    "mockk",
    "turbine",
    "androidx-core-testing",
    "kotlinx-coroutines-test"
]
testing-android = [
    "androidx-test-ext-junit",
    "androidx-espresso-core",
    "androidx-compose-ui-test-junit4"
]
utilities = [
    "timber",
    "coil-compose",
    "androidx-work-runtime",
    "commons-io",
    "commons-compress",
    "xz"
]
xposed = [
    "yuki",
    "lsposed"
]